### PR TITLE
chore(deps): update dependencies

### PR DESCRIPTION
**Pull request by sidvishnoi**
## Context

Instead of merging separate PRs and adding noise to commit log, maybe we should merge PRs combined weekly? This PR was generated with [`ncu`](https://www.npmjs.com/package/npm-check-updates). I've been using this approach on the open-source projects I maintain. We'd let dependabot/renovate generate PRs, but instead of merging each separately, we do this.

See also: https://github.com/interledger/web-monetization-extension/pull/270

## Changes proposed in this pull request

1. Closes #225
2. Closes #304
3. Closes #308 
4. Closes #309 
5. Closes #310 
6. Closes #312 
7. Closes #314
8. and some more dependencies updated.

### CODE REVIEW

**Comment by raducristianpopa** [comment]
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">34f4fe73038cd3e95b4657edf2b459c17b08f75d</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/9449105029">Run #9449105029</a></td>
  </tr>
  <tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/24725994930/artifacts/1585513411">Download</a></td></tr><tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/24725994930/artifacts/1585513415">Download</a></td></tr>
</tbody>
</table>

**Comment by raducristianpopa** [comment]
I don't think we should batch all the dependencies updates. This way, we can easily revert the PR if things are not going as planned.

**Comment by sidvishnoi** [comment]
I'm of opinion that PR is the place where we check things are going right or not. Reverts are exceptional.
Besides, non-major dependency updates are considered safe enough.

I'm mostly concerned about the noise in git log. We've more dependency commits than actual code commits.

**Comment by sidvishnoi** [comment]
From safety perspective, perhaps we can do certain updates (like open payments package) individually. Best of both?

**Comment by sidvishnoi** [comment]
Closing the PR as most dependencies are merged already, but would like a discussion on reducing the dependency PR noise sometime soon.

**Pull request closed without merging**
