### PR TITLE
fix(background): setup payment sessions again on resume if lost

### PR DESCRIPTION
**Pull request by sidvishnoi**
## Context

Closes https://github.com/interledger/web-monetization-extension/issues/413

### CODE REVIEW

**Comment by raducristianpopa** [comment]
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">a01acce34bcf3749acc2018b02a7536eaae692b6</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/9872887612">Run #9872887612</a></td>
  </tr>
  <tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/25840149953/artifacts/1686066219">Download</a></td></tr><tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/25840149953/artifacts/1686066220">Download</a></td></tr>
</tbody>
</table>

**Comment by raducristianpopa** [comment]
In one of the implementation details call we said that we are going to keep the service worker (alarms APi or something else) alive. Why would we need this, if we are going to keep the worker alive?

**Comment by sidvishnoi** [comment]
Hmmm, yeah I forgot about that lol. Let's file an issue for that.

Alternatively, also consider why we might not want to keep background alive (negative effect on battery etc.) and if we can run background as needed.

**Comment by sidvishnoi** [comment]
Closing in favor of https://github.com/interledger/web-monetization-extension/issues/416

**Pull request closed without merging**
