### PR TITLE
docs(TESTING): add testing doc with rafiki.money

### PR DESCRIPTION
**Pull request by sidvishnoi**

### CODE REVIEW

**Comment by raducristianpopa** [comment]
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">7a19906cf9a8e9c9783a01c0f39b0a0deaaab77a</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/10264698937">Run #10264698937</a></td>
  </tr>
  <tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/26850616639/artifacts/1780363752">Download</a></td></tr><tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/26850616639/artifacts/1780363754">Download</a></td></tr>
</tbody>
</table>

**Comment by tselit** [comment]
@sidvishnoi and @raducristianpopa it may be useful to refer to the following text, if not then please disregard: go to the "Getting Started" section of this forum discussion: https://github.com/interledger/web-monetization-extension/discussions/289

**Comment by sidvishnoi** [comment]
@tselit Yes, we referred to it also. But for this document, we need a stable doc for basic setup (not something we want users to test in specific releases).
Note that, this document is essentially https://openpayments.dev/snippets/before-you-begin/  but adapted to extension use case. We'd love this document to live on webmonetization.org

**Comment by melissahenderson** [comment]
Do we need the "Obtain a public-private key pair and key ID" steps for the WM extension doc?

**Comment by sidvishnoi** [comment]
> Do we need the "Obtain a public-private key pair and key ID" steps for the WM extension doc?

@melissahenderson We forgot to update heading there. We actually want a "How to add public key from extension to rafiki.money"

**Comment by sidvishnoi** [comment]
Developer's guide mostly answers this now, even if not as detailed on each step.

**Pull request closed without merging**
