### PR TITLE
feat: use new icons and alert behavior

### PR DESCRIPTION
**Pull request by sidvishnoi**
Closes https://github.com/interledger/web-monetization-extension/issues/373

### CODE REVIEW

**Comment by raducristianpopa** [comment]
<h2>Extension builds preview</h2>

<table role="table">
<thead>
  <tr>
    <th>Name</th>
    <th>Link</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">Latest commit</td>
    <td align="center">cf80f4b7fd85eedff912cc3e6e57a4aefd58e222</td>
  </tr>
  <tr>
    <td align="center">Latest job logs</td>
    <td align="center"><a href="https://github.com/interledger/web-monetization-extension/actions/runs/9661452447">Run #9661452447</a></td>
  </tr>
  <tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/25286402700/artifacts/1635616512">Download</a></td></tr><tr><td align="center">Badge</td><td align="center"><a href="https://github.com/interledger/web-monetization-extension/suites/25286402700/artifacts/1635616514">Download</a></td></tr>
</tbody>
</table>

**Comment by sidvishnoi** [comment]
Preview
image
image


I still think design-wise we're not taking all the available space. But the green/orange/red icons look nice.

**Comment by raducristianpopa** [comment]
When opening the extension's popup, I'm getting this error:
image

It looks like the initial storage is not properly set:
image

**Comment by sidvishnoi** [comment]
Does reloading extension fix it? It could be you working on a different branch and then transitioning. https://github.com/interledger/web-monetization-extension/pull/426 didn't introduce any storage changes.

**Comment by raducristianpopa** [comment]
> Does reloading extension fix it? It could be you working on a different branch and then transitioning. #426 didn't introduce any storage changes.

Nope. Not even re-installing for me.

**Comment by sidvishnoi** [comment]
That's weird. How about checking out an older commit?
I'm sure it's something limited to our dev process.

**Comment by raducristianpopa** [comment]
> That's weird. How about checking out an older commit? I'm sure it's something limited to our dev process.

Going to the an older commit works -  ebc1ef8839e01204dae4f72dfc1fabe8337e65d0.

**Review by raducristianpopa — APPROVED** [review]

**Comment by raducristianpopa** [comment]
As a side note, sometimes on non monetized websites the default icon is displayed instead of the `X` one.

**Comment by sidvishnoi** [comment]
That's something I saw too, and will handle with TabState changes.

**Pull request merged**
