### PR TITLE
feat: support split-view in Edge, tab-tiling in Vivaldi

### PR DESCRIPTION
**Pull request by sidvishnoi**
## Context

Closes https://github.com/interledger/web-monetization-extension/issues/67

Why:
- In Edge, `browser.tabs.query()` skips tabs in right-pane of split-view, as if it don't exist. So, we need to keep track of existing tabs in a window ourselves.
- Similarly, we can't know which tab was last focused.
- There's no API to tell which all tabs are visible (that can be monetized) in a Edge split-view or Vivaldi tab-tiling view.

## Changes proposed in this pull request

- Fire a `TAB_FOCUSED` event from content script, on load (if focused) and on focus change (if focused).
- Use the `sender.tab.id` from above event to store last focused tabId for given window.
- Store that info in newly added `WindowState` service.
- Also store last focused window in above service.
- Note: Both pages in split-mode are monetized together.
- For Edge, if we call `browser.action.setIcon()` with a tabId, it'll only update the icon for the left pane. So, added a `browserName` value, and skip using `tabId` for Edge when setting icon. This will set a global icon for Edge, but other browsers stay like before.
- Instead of relying on `onActivatedTab` which is buggy in Edge with split-view, rely on `TAB_FOCUSED` events' `sender.tab.id` to update icon state. Also use this last focused tab to show popup content.
- In order to support start/stop monetizing all tabs in given view on window focus change (not same as `visibilitychange`, which works like before), we send `IS_TAB_IN_VIEW` message to content script (top frame only) to know if tab is currently visible. This way, we get all visible tabs in current window.
- Remove `IS_WM_ENABLED` message as unused.
- Made some improvements to avoid needless checking need to pause/resume on focus change when extension popup is opened.

For reviewers: Radu is on vacation so I was asked to ask you good folks instead.

## To be decided

Right now, the rate of pay is decided per tab, using the global rate of pay. Now we have multiple active visible tabs getting monetized, so the effective global rate of pay is multiplied by number of active visible tabs - user is paying more than they initially set to as they're paying multiple websites at once. In future, we'll have exception lists (https://github.com/interledger/web-monetization-extension/issues/146), which will again make rate of pay per site/tab.

### CODE REVIEW

**Comment by sidvishnoi** [comment]
If we ignore `tabId` when setting icon in Edge, icon update works fine too. But as it's inefficient, we'll do it only for Edge.

[Screencast from 17-09-24 07:48:39 PM IST.webm](https://github.com/user-attachments/assets/29da469b-e82a-4be8-a4a5-aa4b1e10cd45)

**Comment by sidvishnoi** [comment]
TODO: handle start/resume for all open tabs in split mode, not just left pane.

**Comment by sidvishnoi** [comment]
Demo with Vivaldi tab-tiling!

[Screencast from 18-09-24 06:53:57 PM IST.webm](https://github.com/user-attachments/assets/2dad11ab-bbcc-440e-9e66-4b6df1f70a4a)

**Review by Tymmmy — APPROVED** [review]
While I wasn't able to actually run this right now to see the split view on Edge (nothing to do with you, but with my local current setup), the code looks good to me.

**Comment by Tymmmy** [comment]
@sidvishnoi I have to ask, is this story ready to review? Since I reviewed it and gave approval, you pushed at least 5 new commits. I am asking so that we know when to actually review?

**Review by Tymmmy — APPROVED** [review]
LGTM, surprised we support Edge :)

**Review by lengyel-arpad85 — APPROVED** [review]

**Pull request merged**
